/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.onlinecabbookingmanagementsystem;
import com.mysql.cj.x.protobuf.MysqlxCrud.Update;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class DriverRegistration extends javax.swing.JFrame {

    /**
     * Creates new form DriverRecord
     */
    public DriverRegistration() {
        initComponents();
        
         java.net.URL imgURL = getClass().getResource("file:/C:/Users/hp/OneDrive/Documents/NetBeansProjects/OnlineCabBookingManagementSystem/src/driver-removebg-preview.png");
        if (imgURL != null) {
            ImageIcon icon = new ImageIcon(imgURL);
            jLabel8.setIcon(icon);
        } else {
            System.err.println("Couldn't find file:C:file:/C:/Users/hp/OneDrive/Documents/NetBeansProjects/OnlineCabBookingManagementSystem/src/driver-removebg-preview.png");
        }
        
    }

    int id=0;
int getId()
{
    ResultSet rs=null;
    try
    {
    Class.forName("com.mysql.cj.jdbc.Driver");
String url ="jdbc:mysql://localhost:3306/onlinecbmsystemdatabase?zeroDateTimeBehavior=CONVERT_TO_NULL ";
Connection con=DriverManager.getConnection(url, "root","7217296337@abhi");

String sql="select max(id) from driverregistration";
Statement st=con.createStatement();
rs=st.executeQuery(sql);

while(rs.next())
{
    id=rs.getInt(1);
id++;
}

    }
    catch(Exception e)
    {
    e.printStackTrace();
    }

return id;
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtcnumber = new javax.swing.JTextField();
        txtdob = new com.toedter.calendar.JDateChooser();
        rbmale = new javax.swing.JRadioButton();
        rbfemale = new javax.swing.JRadioButton();
        txtemailid = new javax.swing.JTextField();
        txtpfield = new javax.swing.JPasswordField();
        combol_type = new javax.swing.JComboBox<>();
        txtlnumber = new javax.swing.JTextField();
        txtedate = new com.toedter.calendar.JDateChooser();
        txtcrnumber = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        txtstate = new javax.swing.JTextField();
        comboexperience = new javax.swing.JComboBox<>();
        btnsubmit = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnsignup = new javax.swing.JButton();
        lblpassworderror = new javax.swing.JLabel();
        combocabtype = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Driver Registration");

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\OneDrive\\Documents\\NetBeansProjects\\OnlineCabBookingManagementSystem\\src\\driver-removebg-preview.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addContainerGap())))
        );

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("First_Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 26, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Last_Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 26, 109, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("D.O.B");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 79, 110, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Gender");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 79, 72, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Contact");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 132, 110, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Email_Id");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 132, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Password");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 185, 110, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("License _Type");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 185, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("License_Number");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 238, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("License_Expiry_Date");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 242, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Cab_Type");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 293, 141, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Car_Reg_Number");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 293, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Address");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 346, 141, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("City");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 346, 43, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("State");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 399, 141, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Experience");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 399, -1, -1));

        txtfname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 27, 122, -1));

        txtlname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 27, 123, -1));

        txtcnumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtcnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcnumberActionPerformed(evt);
            }
        });
        jPanel2.add(txtcnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 133, 122, -1));

        txtdob.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 84, 122, -1));

        buttonGroup1.add(rbmale);
        rbmale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbmale.setText("male");
        jPanel2.add(rbmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 81, -1, -1));

        buttonGroup1.add(rbfemale);
        rbfemale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbfemale.setText("female");
        jPanel2.add(rbfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(972, 81, -1, -1));

        txtemailid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(txtemailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 133, 123, -1));

        txtpfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpfieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpfieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpfieldKeyTyped(evt);
            }
        });
        jPanel2.add(txtpfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 186, 122, -1));

        combol_type.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        combol_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Light", "Heavy", "Commerical" }));
        jPanel2.add(combol_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 186, 123, -1));

        txtlnumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(txtlnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 239, 122, -1));

        txtedate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.add(txtedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 242, 123, -1));

        txtcrnumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(txtcrnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 294, 123, -1));

        txtaddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 347, 122, -1));

        txtcity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 347, 123, -1));

        txtstate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(txtstate, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 400, 122, -1));

        comboexperience.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboexperience.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 year", "2 year", "5 year", "10 year" }));
        jPanel2.add(comboexperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 400, 115, -1));

        btnsubmit.setBackground(new java.awt.Color(255, 204, 0));
        btnsubmit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jPanel2.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 456, -1, -1));

        btnupdate.setBackground(new java.awt.Color(255, 204, 0));
        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 456, -1, -1));

        btnclear.setBackground(new java.awt.Color(255, 204, 0));
        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel2.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 456, -1, -1));

        btnback.setBackground(new java.awt.Color(255, 204, 0));
        btnback.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel2.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 456, -1, -1));

        btnsignup.setBackground(new java.awt.Color(255, 204, 0));
        btnsignup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsignup.setText("Sign Up");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        jPanel2.add(btnsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 456, -1, -1));

        lblpassworderror.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(lblpassworderror, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 185, 191, 27));

        combocabtype.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        combocabtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mini", "Micro", "Sedan", "SUV", "Luxury" }));
        jPanel2.add(combocabtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcnumberActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
      Validation();
        if(Validation()==true)
{
    insertData();
}
else
{
JOptionPane.showMessageDialog(this,"validation issue");
}    
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed

        updateDriverDetails(); // TODO add your handling code here:
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
      
txtfname.setText("");
txtlname.setText("");
txtdob.setDate(null);
buttonGroup1.clearSelection();  
txtcnumber.setText("");
txtemailid.setText("");
txtpfield.setText("");
combol_type.setSelectedItem("");
txtlnumber.setText("");
txtedate.setDate(null);
combocabtype.setSelectedItem("");
txtcrnumber.setText("");
txtaddress.setText("");
txtcity.setText("");
txtstate.setText("");
comboexperience.setSelectedItem("");
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
       Home h1 = new Home();
       h1.show();
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
       DriverLogin dl1 = new DriverLogin();
       dl1.show();
       this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btnsignupActionPerformed

    private void txtpfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpfieldKeyPressed
      passwordCheck();   // TODO add your handling code here:
    }//GEN-LAST:event_txtpfieldKeyPressed

    private void txtpfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpfieldKeyReleased
    passwordCheck();     // TODO add your handling code here:
    }//GEN-LAST:event_txtpfieldKeyReleased

    private void txtpfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpfieldKeyTyped
   passwordCheck();      // TODO add your handling code here:
    }//GEN-LAST:event_txtpfieldKeyTyped

    String First_name,Last_name,Gender,Email_id,Password,License_Type,License_Number,Experience,Contact,Cab_Type,Car_Registration_Number,
        Address,City,State;
Date dob , License_Expiry_Date;


  void updateDriverDetails() {
        Connection con = null;
        PreparedStatement st = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/onlinecbmsystemdatabase?zeroDateTimeBehavior=CONVERT_TO_NULL";
            con = DriverManager.getConnection(url, "root", "7217296337@abhi");

            String sql = "update driverregistration SET First_name = ?, Last_name = ?,dob = ?, Gender = ?, Contact = ?, Email_id = ?, Password = ? , License_Type = ?, License_Number = ?, License_Expiry_Date = ?, Cab_Type = ?, Car_Registration_Number= ? , Address = ?, City = ?, State = ?, Experience = ? WHERE Email_id = ? AND Password = ?";
            st = con.prepareStatement(sql);

            st.setString(1, txtfname.getText());
            st.setString(2, txtlname.getText());
        
            java.util.Date dobUtilDate = txtdob.getDate();
        java.sql.Date dobSqlDate = new java.sql.Date(dobUtilDate.getTime());
        st.setDate(3, dobSqlDate);
       
        String gender = rbmale.isSelected() ? rbmale.getText() : rbfemale.getText();
            st.setString(4, gender);
            st.setString(5, txtcnumber.getText());
            st.setString(6, txtemailid.getText());
            st.setString(7, new String(txtpfield.getPassword()));
            st.setString(8, (String) combol_type.getSelectedItem());
            st.setString(9, txtlnumber.getText());

            java.util.Date licenseExpiryDateUtil = txtedate.getDate();
        java.sql.Date licenseExpiryDateSql = new java.sql.Date(licenseExpiryDateUtil.getTime());
        st.setDate(10, licenseExpiryDateSql);
      
        st.setString(11, (String) combocabtype.getSelectedItem());
            st.setString(12, txtcrnumber.getText());
            st.setString(13, txtaddress.getText());
            st.setString(14, txtcity.getText());
            st.setString(15, txtstate.getText());
            st.setString(16, (String) comboexperience.getSelectedItem());
        
            
            st.setString(17, txtemailid.getText());
            st.setString(18, new String(txtpfield.getPassword()));

            int i = st.executeUpdate();
            if (i > 0) {
                JOptionPane.showMessageDialog(null, "Record updated successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Record not updated");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        } finally {
            try {
                if (st != null) st.close();
                if (con != null) con.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
  }
void insertData()
{
    try
    {
        Class.forName("com.mysql.cj.jdbc.Driver");
        String url ="jdbc:mysql://localhost:3306/onlinecbmsystemdatabase?zeroDateTimeBehavior=CONVERT_TO_NULL ";
        Connection con=DriverManager.getConnection(url, "root","7217296337@abhi");
        con.setAutoCommit(false); // disable auto-commit

        String sql = "INSERT INTO driverregistration (id, First_name, Last_name, dob, Gender, Contact, Email_id, Password, License_Type, License_Number, License_Expiry_Date, Cab_Type, Car_Registration_Number, Address, City, State, Experience) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        PreparedStatement st=con.prepareStatement(sql);

        java.util.Date dobUtilDate = txtdob.getDate(); 
        java.sql.Date dobSqlDate = new java.sql.Date(dobUtilDate.getTime());

        java.util.Date License_expiry_DateUtilDate = txtedate.getDate(); 
        java.sql.Date License_expiry_DateSqlDate = new java.sql.Date(License_expiry_DateUtilDate.getTime());

        st.setInt(1, getId());
        st.setString(2, First_name);
        st.setString(3, Last_name);
        st.setDate(4, dobSqlDate); 
        st.setString(5, Gender);
        st.setString(6, Contact);
        st.setString(7, Email_id);
        st.setString(8, Password);
        st.setString(9, License_Type);
        st.setString(10, License_Number);
        st.setDate(11,  License_expiry_DateSqlDate); 
        st.setString(12, Cab_Type);
        st.setString(13, Car_Registration_Number);
        st.setString(14, Address);
        st.setString(15, City);
        st.setString(16, State);
        st.setString(17, Experience);

        st.executeUpdate();
        con.commit(); // commit the changes
        JOptionPane.showMessageDialog(this, "Data inserted successfully");
    }
    catch(Exception e)
    {
        try {
           // con.rollback(); // rollback the changes if an exception occurs
        } 
        catch (Exception b) {
            Logger.getLogger(DriverRegistration.class.getName()).log(Level.SEVERE, null, e);
        }
        JOptionPane.showMessageDialog(this, "Error inserting data: " + e.getMessage());
    }
}

boolean Validation()
{
First_name=txtfname.getText();
Last_name=txtlname.getText();
dob=txtdob.getDate();
if (rbmale.isSelected()) {
        Gender = "Male";
    } else if (rbfemale.isSelected()) {
        Gender = "Female";
    }
Contact=txtcnumber.getText();
Email_id=txtemailid.getText();
Password=txtpfield.getText();
License_Type=(String) combol_type.getSelectedItem();
License_Number=txtlnumber.getText();
License_Expiry_Date= txtedate.getDate();
Cab_Type=(String) combocabtype.getSelectedItem();
Car_Registration_Number=txtcrnumber.getText();
Address=txtaddress.getText();
City=txtcity.getText();
State=txtstate.getText();
Experience=(String) comboexperience.getSelectedItem();

if(First_name.equals(""))    
{
    JOptionPane.showMessageDialog(this, "enter first name");
    return false;
}
if(Last_name.equals(""))    
{
    JOptionPane.showMessageDialog(this, "enter last name");
    return false;
}
if(dob==(null))    
{
    JOptionPane.showMessageDialog(this, "enter date of birth");
    return false;
}
if(Contact.equals(""))    
{
    JOptionPane.showMessageDialog(this, "enter contact number");
    return false;
}
if(Email_id.equals(""))    
{
    JOptionPane.showMessageDialog(this, "enter email id");
    return false;
}
if(Password.equals(""))    
{
    JOptionPane.showMessageDialog(this, "enter password");
    return false;
}
if(License_Type.isEmpty())    
{
    JOptionPane.showMessageDialog(this, "enter License type");
    return false;
}
if(License_Number.equals(""))    
{
    JOptionPane.showMessageDialog(this, "enter License number");
    return false;
}
if(License_Expiry_Date==(null))    
{
    JOptionPane.showMessageDialog(this, "enter license expiry date");
    return false;
}
if(Cab_Type.isEmpty())    
{
    JOptionPane.showMessageDialog(this, "enter car name");
    return false;
}
if(Car_Registration_Number.equals(""))    
{
    JOptionPane.showMessageDialog(this, "enter car registration number");
    return false;
}

 if(Address.equals(""))
{
JOptionPane.showMessageDialog(this,"please enter your address");
return false;
}  
    if(City.equals(""))
{
JOptionPane.showMessageDialog(this,"please enter your city");
return false;
}    
      if(State.equals(""))
{
JOptionPane.showMessageDialog(this,"please enter your state");
return false;
}    
   if(Experience.equals("")) 
   {
       JOptionPane.showMessageDialog(this,"enter experience");
   }
return true;
}
  
void passwordCheck()
{
Password=txtpfield.getText();
if(Password.length()>=8)
{
lblpassworderror.setText("");
}
else
{
lblpassworderror.setText("enter 8 digit password number ");
}
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriverRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriverRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriverRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriverRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DriverRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnsignup;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton btnupdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combocabtype;
    private javax.swing.JComboBox<String> comboexperience;
    private javax.swing.JComboBox<String> combol_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblpassworderror;
    private javax.swing.JRadioButton rbfemale;
    private javax.swing.JRadioButton rbmale;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtcnumber;
    private javax.swing.JTextField txtcrnumber;
    private com.toedter.calendar.JDateChooser txtdob;
    private com.toedter.calendar.JDateChooser txtedate;
    private javax.swing.JTextField txtemailid;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtlnumber;
    private javax.swing.JPasswordField txtpfield;
    private javax.swing.JTextField txtstate;
    // End of variables declaration//GEN-END:variables
}
